### PR TITLE
bugs removed please review

### PR DESCRIPTION
**Pull request by osadeyemo**

### CODE REVIEW

**Review by flawlez18 — COMMENTED** [review]
Review completed. No observation made.

**Review by tunji22 — COMMENTED** [review]
Good to go

**Comment by osadeyemo** [comment]
Great job Team!

"Life is lived forward and understood backwards"

-Anonymous 
 

    On Tuesday, May 31, 2022, 08:42:26 PM CDT, tunji22 ***@***.***> wrote:  
 
 


@tunji22 commented on this pull request.

Good to go

**Comment by alliangue** [comment]
Good to be deployed

**Pull request merged**
